// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWaXy37-r44whSa2mv3ZUScveUAPJPDuo',
    appId: '1:1076497572853:web:c5919b4c4cb4163ec9b6bc',
    messagingSenderId: '1076497572853',
    projectId: 'facebook-clone-39cb9',
    authDomain: 'facebook-clone-39cb9.firebaseapp.com',
    databaseURL: 'https://facebook-clone-39cb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'facebook-clone-39cb9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCobC5P_bT-gCQheDWU4QMbFEBtrMbcNR4',
    appId: '1:1076497572853:android:ccd1ca9991291c3dc9b6bc',
    messagingSenderId: '1076497572853',
    projectId: 'facebook-clone-39cb9',
    databaseURL: 'https://facebook-clone-39cb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'facebook-clone-39cb9.appspot.com',
  );
}
